# generated by datamodel-codegen:
#   filename:  graph_config.yaml
#   timestamp: 2026-08-30T15:22:33+00:00

from __future__ import annotations

from pydantic import BaseModel


class Mcp(BaseModel):
    transport: str
    port: int
    host: str


class TopwrApi(BaseModel):
    host: str
    port: int
    cors_origins: str


class Servers(BaseModel):
    mcp: Mcp
    topwr_api: TopwrApi


class Rag(BaseModel):
    max_results: int
    enable_debug: bool
    llm_timeout_seconds: int
    graph_timeout_seconds: int
    enable_fallback_search: bool
    fallback_min_score: float


class DataPipeline(BaseModel):
    max_chunk_size: int
    chunk_overlap: int
    token_limit: int


class FastModel(BaseModel):
    name: str
    temperature: float


class AccurateModel(BaseModel):
    name: str
    temperature: float


class Clarin(BaseModel):
    name: str
    base_url: str


class Deepseek(BaseModel):
    base_url: str
    fast_model: str
    accurate_model: str


class Gemini(BaseModel):
    name: str


class Llm(BaseModel):
    fast_model: FastModel
    accurate_model: AccurateModel
    provider_fallback_order: list[str]
    clarin: Clarin
    deepseek: Deepseek
    gemini: Gemini


class Langfuse(BaseModel):
    host: str
    secret_key: str
    public_key: str


class Observability(BaseModel):
    langfuse: Langfuse


class Database(BaseModel):
    name: str
    uri: str
    username: str
    password: str


class Prompts(BaseModel):
    final_answer: str
    cypher_insert: str
    schema_reflection: str
    cypher_search: str
    guardrails: str


class Model(BaseModel):
    servers: Servers
    rag: Rag
    data_pipeline: DataPipeline
    llm: Llm
    observability: Observability
    database: Database
    prompts: Prompts
